local hls = function(colors)
	return {
		TitleString = { fg = colors.green, bold = true },
		TitleIcon = { fg = colors.purple },
		SagaBorder = { link = "FloatBorder" },
		SagaNormal = { bg = colors.darker_black },
		SagaExpand = { fg = colors.line },
		SagaCollapse = { fg = colors.line },
		SagaBeacon = { bg = colors.green },
		-- code action
		ActionPreviewNormal = { link = "SagaNormal" },
		ActionPreviewBorder = { link = "SagaBorder" },
		ActionPreviewTitle = { fg = colors.black2, bg = colors.green },
		CodeActionNormal = { link = "SagaNormal" },
		CodeActionBorder = { link = "SagaBorder" },
		CodeActionText = { fg = colors.orange },
		CodeActionNumber = { fg = colors.green },
		-- finder
		FinderSelection = { fg = colors.white, bg = colors.black2, bold = true },
		FinderFileName = { fg = colors.green },
		FinderCount = { link = "Label" },
		FinderIcon = { fg = colors.folder_bg },
		FinderType = { fg = colors.purple },
		--finder spinner
		FinderSpinnerTitle = { fg = colors.purple, bold = true },
		FinderSpinner = { fg = colors.purple, bold = true },
		FinderPreviewSearch = { link = "Search" },
		FinderVirtText = { fg = colors.light_grey },
		FinderNormal = { link = "SagaNormal" },
		FinderBorder = { link = "SagaBorder" },
		FinderPreviewBorder = { link = "SagaBorder" },
		-- definition
		DefinitionBorder = { link = "SagaBorder" },
		DefinitionNormal = { link = "SagaNormal" },
		DefinitionSearch = { link = "Search" },
		-- hover
		HoverNormal = { link = "SagaNormal" },
		HoverBorder = { link = "SagaBorder" },
		-- rename
		RenameBorder = { link = "SagaBorder" },
		RenameNormal = { fg = colors.orange, bg = colors.darker_black },
		RenameMatch = { link = "Search" },
		-- diagnostic
		DiagnosticBorder = { link = "SagaBorder" },
		DiagnosticSource = { fg = "gray" },
		DiagnosticNormal = { link = "SagaNormal" },
		DiagnosticPos = { fg = colors.grey },
		DiagnosticWord = { fg = colors.white },
		-- Call Hierachry
		CallHierarchyNormal = { link = "SagaNormal" },
		CallHierarchyBorder = { link = "SagaBorder" },
		CallHierarchyIcon = { fg = colors.folder_bg },
		CallHierarchyTitle = { fg = colors.red, bold = true },
		-- lightbulb
		LspSagaLightBulb = { link = "DiagnosticSignHint" },
		-- shadow
		SagaShadow = { bg = colors.one_bg },
		-- Outline preview
		OutlineIndent = { fg = colors.line },
		OutlinePreviewBorder = { link = "SagaNormal" },
		OutlinePreviewNormal = { link = "SagaBorder" },
		-- Float term
		TerminalBorder = { link = "SagaBorder" },
		TerminalNormal = { link = "SagaNormal" },
		-- Outline window
		LSOutlineArray = { link = "@type" },
		LSOutlineBoolean = { link = "@boolean" },
		LSOutlineClass = { link = "@class" },
		LSOutlineConstant = { link = "@constant" },
		LSOutlineConstructor = { link = "@constructor" },
		LSOutlineEnum = { link = "@enum" },
		LSOutlineEnumMember = { link = "@enumMember" },
		LSOutlineEvent = { link = "@event" },
		LSOutlineField = { link = "@field" },
		LSOutlineFile = { fg = colors.base07 },
		LSOutlineFolder = { fg = colors.folder_bg },
		LSOutlineFunction = { link = "@function" },
		LSOutlineInterface = { link = "@interface" },
		LSOutlineKey = { link = "Identifier" },
		LSOutlineMacro = { link = "Macro" },
		LSOutlineModule = { link = "@class" },
		LSOutlineNamespace = { link = "@namespace" },
		LSOutlineNull = { link = "@boolean" },
		LSOutlineNumber = { link = "@number" },
		LSOutlineObject = { link = "class" },
		LSOutlineOperator = { link = "Operator" },
		LSOutlinePackage = { fg = colors.base07 },
		LSOutlineParameter = { link = "@parameter" },
		LSOutlineProperty = { link = "@property" },
		LSOutlineSnippet = { fg = colors.base04 },
		LSOutlineString = { link = "@string" },
		LSOutlineStruct = { link = "@struct" },
		LSOutlineText = { link = "@text" },
		LSOutlineTypeAlias = { link = "@type" },
		LSOutlineTypeParameter = { link = "@typeParameter" },
		LSOutlineUnit = { fg = colors.base05 },
		LSOutlineValue = { fg = colors.base05 },
		LSOutlineVariable = { link = "@variable" },
		-- LspSaga winbar
		LspSagaWinbarArray = { link = "@type" },
		LspSagaWinbarBoolean = { link = "@boolean" },
		LspSagaWinbarClass = { link = "@class" },
		LspSagaWinbarConstant = { link = "@constant" },
		LspSagaWinbarConstructor = { link = "@constructor" },
		LspSagaWinbarEnum = { link = "@enum" },
		LspSagaWinbarEnumMember = { link = "@enumMember" },
		LspSagaWinbarEvent = { link = "@event" },
		LspSagaWinbarField = { link = "@field" },
		LspSagaWinbarFile = { fg = colors.base07 },
		LspSagaWinbarFolder = { fg = colors.folder_bg },
		LspSagaWinbarFolderName = { fg = colors.base07 },
		LspSagaWinbarFunction = { link = "@function" },
		LspSagaWinbarInterface = { link = "@interface" },
		LspSagaWinbarKey = { link = "Identifier" },
		LspSagaWinbarMacro = { link = "Macro" },
		LspSagaWinbarModule = { link = "@class" },
		LspSagaWinbarNamespace = { link = "@boolean" },
		LspSagaWinbarNull = { fg = colors.nord_blue },
		LspSagaWinbarNumber = { link = "@number" },
		LspSagaWinbarObject = { link = "@class" },
		LspSagaWinbarOperator = { link = "Operator" },
		LspSagaWinbarPackage = { fg = colors.base07 },
		LspSagaWinbarParameter = { link = "@parameter" },
		LspSagaWinbarProperty = { link = "@property" },
		LspSagaWinbarSep = { link = "Operator" },
		LspSagaWinbarSnippet = { fg = colors.base04 },
		LspSagaWinbarStaticMethod = { link = "@method" },
		LspSagaWinbarString = { link = "@string" },
		LspSagaWinbarStruct = { link = "@struct" },
		LspSagaWinbarText = { link = "@text" },
		LspSagaWinbarTypeAlias = { link = "@type" },
		LspSagaWinbarTypeParameter = { link = "@typeParameter" },
		LspSagaWinbarUnit = { fg = colors.base05 },
		LspSagaWinbarValue = { fg = colors.base05 },
		LspSagaWinbarVariable = { link = "@variable" },
		LspSagaWinbarWord = { link = "@text" },
	}
end
return hls
