local hls = function(colors)
	return {
		NeoTreeBufferNumber = { fg = colors.light_grey },
		NeoTreeCursorLine = { bg = colors.black2 },
		NeoTreeDimText = { fg = colors.light_grey },
		NeoTreeDirectoryIcon = { fg = colors.folder_bg },
		NeoTreeDirectoryName = { fg = colors.white },
		NeoTreeDotfile = { fg = colors.light_grey, italic = true },
		NeoTreeFileIcon = { fg = colors.folder_bg },
		NeoTreeFileName = { fg = colors.white },
		NeoTreeFileNameOpened = { fg = colors.white },
		NeoTreeFilterTerm = { fg = colors.white },
		NeoTreeFloatBorder = { link = "FloatNormal" },
		NeoTreeFloatTitle = { fg = colors.white, bold = true },
		NeoTreeTitleBar = { bg = colors.darker_black },
		NeoTreeGitAdded = { fg = colors.white },
		NeoTreeGitConflict = { fg = colors.red },
		NeoTreeGitDeleted = { fg = colors.baby_pink },
		NeoTreeGitIgnored = { fg = colors.grey },
		NeoTreeGitModified = { fg = colors.nord_blue },
		NeoTreeGitUnstaged = { fg = colors.yellow },
		NeoTreeGitUntracked = { fg = colors.cyan },
		NeoTreeGitStaged = { fg = colors.white },
		NeoTreeHiddenByName = { fg = colors.one_bg3, italic = true },
		NeoTreeIndentMarker = { fg = colors.black2 },
		NeoTreeExpander = { fg = colors.folder_bg },
		NeoTreeNormal = { bg = colors.darker_black },
		NeoTreeNormalNC = { bg = colors.darker_black },
		NeoTreeSignColumn = { link = "SignColumn" },
		NeoTreeStatusLine = { bg = colors.darker_black },
		NeoTreeStatusLineNC = { bg = colors.darker_black },
		NeoTreeVertSplit = { fg = colors.black2 },
		NeoTreeWinSeparator = { fg = colors.black2, bg = colors.darker_black },
		NeoTreeEndOfBuffer = { fg = colors.white },
		NeoTreeRootName = { fg = colors.white, italic = true },
		NeoTreeSymbolicLinkTarget = { fg = colors.vibrant_green, italic = true },
		NeoTreeWindowsHidden = { fg = colors.light_grey },
		NeoTreeTabActive = { fg = colors.black, bg = colors.pmenu_bg, bold = true },
		NeoTreeTabInactive = { fg = colors.light_grey, bg = colors.black },
		NeoTreeTabSeparatorInactive = { fg = colors.light_grey, bg = "NONE" },
		NeoTreeTabSeparatorActive = { fg = colors.pmenu_bg, bg = colors.pmenu_bg },
	}
end
return hls
