local hls = function(colors, opts)
	return {
		["@annotation"] = { fg = colors.base0F },
		["@attribute"] = { fg = colors.base0A },
		["@boolean"] = { fg = colors.base09 },
		["@character"] = { fg = colors.base08 },
		["@character.special"] = { link = "SpecialChar" },
		["@class"] = { fg = colors.base0A },
		["@comment"] = { fg = colors.base03, italic = opts.italic },
		["@conditional"] = { fg = colors.base0E },
		["@constant"] = { fg = colors.base09 },
		["@constant.builtin"] = { fg = colors.base09, italic = opts.italic },
		["@constant.macro"] = { fg = colors.base09 },
		["@constructor"] = { fg = colors.base0D },
		["@debug"] = { link = "Debug" },
		["@decorator"] = { link = "Identifier" },
		["@define"] = { link = "Define" },
		["@enum"] = { fg = colors.base0A },
		["@enumMember"] = { link = "Constant" },
		["@error"] = { fg = colors.base08 },
		["@event"] = { link = "Identifier" },
		["@exception"] = { fg = colors.base08 },
		["@field"] = { fg = colors.base05 },
		["@float"] = { fg = colors.base09 },
		["@function"] = { fg = colors.base0D },
		["@function.builtin"] = { fg = colors.base0D, italic = opts.italic },
		["@function.call"] = { fg = colors.base0D },
		["@function.macro"] = { fg = colors.base08 },
		["@include"] = { fg = colors.base0D },
		["@interface"] = { link = "Structure" },
		["@keyword"] = { fg = colors.base0E },
		["@keyword.function"] = { fg = colors.base0E },
		["@keyword.operator"] = { fg = colors.base0E },
		["@keyword.return"] = { fg = colors.base0E },
		["@label"] = { fg = colors.base0A },
		["@method"] = { fg = colors.base0D },
		["@method.call"] = { fg = colors.base0D },
		["@modifier"] = { link = "Identifier" },
		["@namespace"] = { fg = colors.base08 },
		["@none"] = { fg = colors.base05 },
		["@number"] = { fg = colors.base09 },
		["@operator"] = { fg = colors.base05 },
		["@parameter"] = { fg = colors.base05 },
		["@preproc"] = { link = "PreProc" },
		["@property"] = { fg = colors.base05 },
		["@punctuation.bracket"] = { fg = colors.base05 },
		["@punctuation.delimiter"] = { fg = colors.base0F },
		["@punctuation.special"] = { fg = colors.base05 },
		["@regexp"] = { fg = colors.base0C },
		["@repeat"] = { fg = colors.base0E },
		["@storageclass"] = { link = "StorageClass" },
		["@strike"] = { strikethrough = true },
		["@string"] = { fg = colors.base0B },
		["@string.escape"] = { fg = colors.base0C },
		["@string.regex"] = { fg = colors.base0C },
		["@string.special"] = { link = "SpecialChar" },
		["@struct"] = { fg = colors.base0A },
		["@symbol"] = { fg = colors.base0B },
		["@tag"] = { fg = colors.base0A },
		["@tag.attribute"] = { fg = colors.base0A },
		["@tag.delimiter"] = { fg = colors.base0F },
		["@text"] = { fg = colors.base05 },
		["@text.danger"] = { link = "DiagnosticError" },
		["@text.diff.add"] = { link = "DiffAdd" },
		["@text.diff.delete"] = { link = "DiffDelete" },
		["@text.emphasis"] = { fg = colors.base09, italic = opts.italic },
		["@text.environment"] = { link = "Macro" },
		["@text.environment.name"] = { link = "Type" },
		["@text.literal"] = { fg = colors.base09 },
		["@text.math"] = { link = "Number" },
		["@text.note"] = { link = "Tag" },
		["@text.reference"] = { fg = colors.base05 },
		["@text.strong"] = { bold = opts.bold },
		["@text.title"] = { fg = colors.base0D },
		["@text.todo"] = { link = "Todo" },
		["@text.underline"] = { fg = colors.base00, underline = opts.underline },
		["@text.uri"] = { fg = colors.base09, underline = opts.underline },
		["@text.warning"] = { link = "DiagnosticWarn" },
		["@type"] = { fg = colors.base0A },
		["@type.builtin"] = { fg = colors.base0A, italic = opts.italic },
		["@type.definition"] = { fg = colors.base0A },
		["@typeParameter"] = { fg = colors.base0A },
		["@type.qualifier"] = { fg = colors.base0A },
		["@variable"] = { fg = colors.base08 },
		["@variable.builtin"] = { fg = colors.base08, italic = opts.italic },
	}
end
return hls
